export enum textTypes {

    //TITLE
    TITLE_BOLD = 'TITLE_BOLD', //24px
    TITLE_SEMIBOLD = 'TITLE_SEMIBOLD', 
    TITLE_REGULAR = 'TITLE_REGULAR', 
    TITLE_LIGHT = 'TITLE_LIGHT', 
    
    //SUBTITLE
    SUBTITLE_BOLD = 'SUBTITLE_BOLD', //20px
    SUBTITLE_SEMIBOLD = 'SUBTITLE_SEMIBOLD', 
    SUBTITLE_REGULAR = 'SUBTITLE_REGULAR', 
    SUBTITLE_LIGHT = 'SUBTITLE_LIGHT', 
    
    //PARAGRAPH
    PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //14px
    PARAGRAPH_SEMIBOLD = 'PARAGRAPH_SEMIBOLD', 
    PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR', 
    PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT', 
    
    //PARAGRAPH_SMALL
    PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD', //10px
    PARAGRAPH_SMALL_SEMIBOLD = 'PARAGRAPH_SMALL_SEMIBOLD', 
    PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR', 
    PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT', 

}